export DB_CONNECTION_STRING='User ID=test_user;Password=test_password;Host=104.40.181.96;Port=5432;Database=test_db;Pooling=true;Keepalive=25'
export RABBITMQ_CONNECTION_USERNAME='guest'
export RABBITMQ_CONNECTION_PASSWORD='guest'
export RABBITMQ_CONNECTION_PORT='5672'
export RABBITMQ_CONNECTION_VHOST='test'
export RABBITMQ_CONNECTION_HOSTNAME='172.17.0.2'
export SFTP_CONNECTION_HOST='hbftptest.westeurope.cloudapp.azure.com'
export SFTP_CONNECTION_PORT='22'
export SFTP_CONNECTION_USERNAME='nkrokhmal'
export SFTP_CONNECTION_PASSWORD='kloppolk_2018'
export SFTP_CONNECTION_DESTINATIONPATH='/home/nkrokhmal/storage/'
export SFTP_CONNECTION_DOWNLOADPATH='/opt/download/'
